### PR TITLE
Minor doc fixes

### PR DESCRIPTION
**Pull request by paultcochrane**
This PR improves sentence flow in the documentation a bit and fixes other minor issues.  I've split up the commits so that they can be cherry-picked if so desired.  For instance, I've made the assumption that American spelling should be used (as is often the case with technical documentation); however, I suspect you might have wanted the Canadian spelling (which seems to often follow the British spelling conventions), hence cherry-picking might be the best thing.  If you want these commits rolled into one commit so that the history is nicer, I don't have a problem with doing that and can resubmit the PR.

### CODE REVIEW

**Comment by paultcochrane** [comment]
Just a side question: after having looked at the repository and its branches, I got the impression that one should base pull requests off the `master` branch rather than the `releases` branch.  Is that correct?  Also: would contributor documentation be helpful?  That way there could be a guide for people who want to set up a development environment and submit patches, and they can thus submit PRs in a form that makes them easier for you to merge.  Just a thought :-)

**Comment by yanick** [comment]
> I got the impression that one should base pull requests off the master branch rather than the releases branch. Is that correct?

If you can, basing the PRs out of `master` is prefered. But since I use Dist::Zilla in a rather, ah, hard-core manner, I recognize that it's not everyone's cup of tea and I'm perfectly willing to port the PRs from `releases` back to `master`. :-)

**Comment by yanick** [comment]
> would contributor documentation be helpful? That way there could be a guide for people who want to set up a development environment and submit patches, and they can thus submit PRs in a form that makes them easier for you to merge. Just a thought :-)

Sure! Bear in mind, though, that Dancer 1 is superseded by Dancer 2, so contributions to this module are expected to slowly dwindle to nothing.  But if you feel like it, hey, more documentation is always good documentation. :-)  I'm even pretty sure there is a Dist::Zilla plugin somewhere that would provide you with a decent template for it too.

**Comment by yanick** [comment]
> I've split up the commits so that they can be cherry-picked if so desired.

That's the way I prefer it, thank you so much. ^.^  That way, I can always merge it all like a savage if I feel like it, but if there any specific decision I don't agree with, it's much easier to not pick it up as-is.

**Pull request closed without merging**
